import type { Metadata } from "next";
import { Inter,Outfit, Odibee_Sans } from "next/font/google";
import Navbar from "../components/Navbar";
import React from "react";
// import "./globals.css";



export const metadata: Metadata = {
  title: "SwiftSci",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar></Navbar>
        <React.Fragment>

          {children}  
        </React.Fragment>
      </body>
    </html>
  );
}
