FROM python:alpine

WORKDIR /app

COPY requirements.txt ./

RUN pip install bson
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# Start the Flask application
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "wsgi:app"]


