import type { Metadata } from "next";
import { Inter , Outfit, Poppins, Montserrat, Lato } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const outift = Outfit({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "SwiftSci",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outift.className}>
        <ToastContainer></ToastContainer>
        {children}
      </body>
    </html>
  );
}
