import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import PaperSidebar from "../components/PaperSidebar";
import React from "react";

// import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex w-screen bg-primary h-screen">

          <PaperSidebar></PaperSidebar>
          {children}  

          
        </main>
      </body>
    </html>
  );
}
