name: AWS EC2 Deployment Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/**'
  pull_request:
    branches:
      - main

jobs:

  deploy:
      # needs: build-and-test
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kaane0169/swiftsci-backend:latest
          context: ./server
          file: ./server/Dockerfile

      - name: Retrieve and Run Docker Images on EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ec2-user@${{ secrets.EC2_HOST }} 'bash -s' << 'ENDSSH'

            
            sudo docker pull kaane0169/swiftsci-backend:latest
            sudo docker stop swiftsci-backend || true
            sudo docker rm swiftsci-backend || true
            sudo docker run -d --name swiftsci-backend -p 80:5000 --env-file ./.env kaane0169/swiftsci-ec2

          ENDSSH

      